<?php

namespace ContactBoxBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PersonGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonGroupRepository extends EntityRepository
{
}
